apiVersion: v1
kind: Service
metadata:
  name: docspell-joex
  labels:
    app: docspell-joex
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 7878
      targetPort: 7878
      protocol: TCP
      name: api
  selector:
    app: docspell-joex