apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "docspell.fullname" . }}-restserver
  labels:
    {{- include "docspell.labels" . | nindent 4 }}
    docspell-component: restserver
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "docspell.selectorLabels" . | nindent 6 }}
      docspell-component: restserver
  template:
    metadata:
      labels:
        {{- include "docspell.selectorLabels" . | nindent 8 }}
        docspell-component: restserver
        config-hash: {{ .Values.restserver.config | adler32sum | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: restserver
        image: {{ print .Values.restserver.image.repo ":" (.Values.restserver.image.tag | default .Values.image.tag | default (print "v" .Chart.AppVersion)) | quote }}
        imagePullPolicy: {{ .Values.restserver.image.pullPolicy | default .Values.image.pullPolicy | quote }}
        args: ['/opt/docspell.conf']
        envFrom:
        - secretRef:
            name: {{ .Values.jdbc.credentialsSecretName }}
        volumeMounts:
        - name: config
          mountPath: /opt/docspell.conf
          subPath: config
        ports:
        - name: api
          containerPort: {{ .Values.restserver.bindPort }}
          protocol: TCP
      volumes:
      - name: config
        secret:
          secretName: {{ include "docspell.fullname" . }}-restserver-config
